# Generated by Django 4.2.7 on 2023-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="following_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_Image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
