# Generated by Django 4.2.7 on 2023-11-29 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0002_alter_user_followers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='Like',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='userr.user'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='Retweet_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Retweet', to='userr.tweets'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweeted_user', to='userr.user'),
        ),
    ]
